ecommerce:
  target: dev
  outputs:
    dev:
      account: CVOHIOR-OY32875
      database: ECOMMERCE
      password: nike@123
      role: PIPELINE_ROLE
      schema: RAW
      threads: 4
      type: snowflake
      user: PIPELINE_USER
      warehouse: ECOMM_WH
    prod:
      account: CVOHIOR-OY32875
      database: ECOMMERCE
      password: nike@123
      role: PIPELINE_ROLE
      schema: STAGING
      threads: 8
      type: snowflake
      user: PIPELINE_USER
      warehouse: ECOMM_WH
  
